"""Web layer — Jinja-based server-rendered UI (ADR-0030, ADR-0029).

Templates under ``templates/``, static assets under ``static/``. Only reads
from ``mart.*`` by AST-lint invariant; the UI never joins ``core.*`` or
``stg.*`` directly.
"""
from new_nfl.web.assets import StaticAssetResolver, static_asset_path
from new_nfl.web.freshness import (
    FreshnessRow,
    HomeOverview,
    build_home_overview,
    load_freshness_rows,
)
from new_nfl.web.game_view import (
    BoxscorePlayer,
    GameDetail,
    GameMeta,
    TeamSideForm,
    TeamSideWeek,
    get_game_detail,
)
from new_nfl.web.games_view import (
    GameRow,
    SeasonSummary,
    WeekSummary,
    list_games,
    list_seasons,
    list_weeks,
)
from new_nfl.web.player_view import (
    PlayerCard,
    PlayerCareerSnapshot,
    PlayerListPage,
    PlayerMeta,
    PlayerProfile,
    PlayerRosterInterval,
    PlayerSeasonStatsRow,
    get_player_profile,
    list_players,
)
from new_nfl.web.provenance_view import (
    ProvenanceListPage,
    ProvenanceRecord,
    get_provenance,
    list_provenance,
)
from new_nfl.web.renderer import (
    WebRenderer,
    build_renderer,
    render_game_detail_page,
    render_home,
    render_home_from_settings,
    render_player_profile_page,
    render_players_page,
    render_provenance_detail_page,
    render_provenance_page,
    render_run_detail_page,
    render_runs_page,
    render_season_weeks_page,
    render_seasons_page,
    render_team_profile_page,
    render_teams_page,
    render_week_games_page,
)
from new_nfl.web.run_view import (
    RunArtifactRow,
    RunDetail,
    RunEventRow,
    RunListPage,
    RunSummary,
    get_run_detail,
    list_runs,
)
from new_nfl.web.team_view import (
    RosterEntry,
    TeamCard,
    TeamGameRow,
    TeamMeta,
    TeamProfile,
    TeamSeasonStatsRow,
    get_team_profile,
    list_teams,
)

__all__ = [
    "BoxscorePlayer",
    "FreshnessRow",
    "GameDetail",
    "GameMeta",
    "GameRow",
    "HomeOverview",
    "PlayerCard",
    "PlayerCareerSnapshot",
    "PlayerListPage",
    "PlayerMeta",
    "PlayerProfile",
    "PlayerRosterInterval",
    "PlayerSeasonStatsRow",
    "ProvenanceListPage",
    "ProvenanceRecord",
    "RosterEntry",
    "RunArtifactRow",
    "RunDetail",
    "RunEventRow",
    "RunListPage",
    "RunSummary",
    "SeasonSummary",
    "StaticAssetResolver",
    "TeamCard",
    "TeamGameRow",
    "TeamMeta",
    "TeamProfile",
    "TeamSeasonStatsRow",
    "TeamSideForm",
    "TeamSideWeek",
    "WebRenderer",
    "WeekSummary",
    "build_home_overview",
    "build_renderer",
    "get_game_detail",
    "get_player_profile",
    "get_provenance",
    "get_run_detail",
    "get_team_profile",
    "list_games",
    "list_players",
    "list_provenance",
    "list_runs",
    "list_seasons",
    "list_teams",
    "list_weeks",
    "load_freshness_rows",
    "render_game_detail_page",
    "render_home",
    "render_home_from_settings",
    "render_player_profile_page",
    "render_players_page",
    "render_provenance_detail_page",
    "render_provenance_page",
    "render_run_detail_page",
    "render_runs_page",
    "render_season_weeks_page",
    "render_seasons_page",
    "render_team_profile_page",
    "render_teams_page",
    "render_week_games_page",
    "static_asset_path",
]
